import { createPrivateKey, createPublicKey, type KeyObject } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { b64url, localSigner, providerId, rawPublicKey, signChannelList, signDocument, type Keyset } from '@sanpo-console/protocol';
import { sampleChannel } from '@sanpo-console/protocol/testing';

/**
 * Test vectors for the app's own checks of API-002 (SanpoGuide station-format): a discovery
 * document, a channel list and a test ticket, signed by this repository's code with fixed keys.
 * Ed25519 is deterministic, so the output never changes unless the format does.
 *
 *   npm run vectors -w conformance -- ../SanpoGuide/station-format/src/test/resources/provider-vectors.json
 *
 * The keys come from fixed seeds and are public: never use them for a real provider.
 */
const PKCS8_ED25519 = Buffer.from('302e020100300506032b657004220420', 'hex');
const fromSeed = (byte: number): KeyObject => createPrivateKey({ key: Buffer.concat([PKCS8_ED25519, Buffer.alloc(32, byte)]), format: 'der', type: 'pkcs8' });
const publicOf = (key: KeyObject) => rawPublicKey(createPublicKey(key));

const root = fromSeed(1);
const signing = fromSeed(2);
const rootKey = publicOf(root);
const provider = providerId(rootKey);
const publisher = 'sg1' + 'b'.repeat(32);

const keyset: Keyset = {
  type: 'keyset', provider, seq: 2, issuedAt: '2026-10-01T00:00:00.000Z',
  keys: [{ keyId: 'k-2026-10', publicKey: b64url.encode(publicOf(signing)), notBefore: '2026-10-01T00:00:00.000Z', notAfter: '2027-04-01T00:00:00.000Z' }],
  revokedKeys: ['k-2026-04'],
};
const discovery = {
  provider, name: '検証用の提供元', versions: ['v1'], list: '/v1/channels.json', rootKey: b64url.encode(rootKey),
  keyset: await signDocument(keyset, localSigner(provider, root)),
  reviewPolicyUrl: 'https://example.com/policy',
};
const signer = localSigner('k-2026-10', signing);
const list = await signChannelList(
  {
    provider, seq: 7, issuedAt: new Date('2026-10-03T03:00:00.000Z'), expiresAt: new Date('2026-10-17T03:00:00.000Z'),
    channels: [
      sampleChannel({ publisher, description: '寺社と武士の歴史', tags: ['history'], regions: ['xn7'], publisherChange: { from: 'sg1' + 'a'.repeat(32), at: '2026-10-02T09:00:00.000Z', reason: '配信元の鍵の紛失' } }),
      sampleChannel({ id: 'tokyo-nature', version: 1, publisher, name: '東京の自然', summary: '公園と水辺', minAppVersion: 99 }),
    ],
    revoked: [{ id: 'old-channel', versions: [1, 2], reason: '審査基準に反する内容が見つかったため', revokedAt: '2026-10-01T00:00:00.000Z' }],
  },
  signer,
);
const ticket = await signDocument(
  {
    type: 'test-ticket', provider, channel: 'kamakura-history', publisher,
    package: { url: 'https://cdn.example.com/trial/x.zip', sha256: '1'.repeat(64), size: 18342, format: 1 },
    issuedAt: '2026-10-03T03:00:00.000Z', expiresAt: '2026-10-10T03:00:00.000Z',
  },
  signer,
);

const out = process.argv[2] ?? 'provider-vectors.json';
writeFileSync(
  out,
  `${JSON.stringify(
    {
      note: 'Generated by sanpo-channel-console conformance/src/app-vectors.ts with fixed, public keys. Do not edit by hand.',
      provider,
      discovery,
      list: list.document,
      ticket,
      // Valid for all three documents.
      now: '2026-10-05T00:00:00.000Z',
    },
    null,
    2,
  )}\n`,
);
console.log(`wrote ${out} for provider ${provider}`);
