/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ログインしているユーザー・役割・配信元 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publisher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の配信元 */
        get: operations["getMyPublisher"];
        put?: never;
        /** 配信元として登録（pending_key） */
        post: operations["registerPublisher"];
        /** 退会（公開中のチャンネルはすべて取り下げる） */
        delete: operations["deleteMyPublisher"];
        options?: never;
        head?: never;
        /** 表示名・連絡先の変更 */
        patch: operations["updateMyPublisher"];
        trace?: never;
    };
    "/api/publisher/keys/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 鍵の紐づけ用の一度きりの文字列（10 分） */
        post: operations["createKeyChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publisher/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 鍵の一覧（今のものと過去のもの） */
        get: operations["listMyKeys"];
        put?: never;
        /** 最初の鍵を紐づける */
        post: operations["bindFirstKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publisher/key-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 移し替えの申し出の一覧 */
        get: operations["listMyKeyTransfers"];
        put?: never;
        /** 新しい鍵を紐づけて移し替えを申し出る */
        post: operations["requestKeyTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publisher/key-transfers/{transferId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移し替えの申し出を取り消す */
        post: operations["cancelKeyTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publisher/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の配信元・チャンネルの経緯 */
        get: operations["listMyHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分のチャンネルの一覧 */
        get: operations["listMyChannels"];
        put?: never;
        /** チャンネル ID を登録 */
        post: operations["registerChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        /** チャンネル（配信元は自分のもの、運用者はすべて） */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        /** 申請の一覧（新しい順） */
        get: operations["listSubmissions"];
        put?: never;
        /** 申請を作り、アップロード先を受け取る */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** 申請（機械審査の結果、判定と理由） */
        get: operations["getSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}/submissions/{submissionId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 申請を取り消す（awaiting_review・in_review のとき） */
        post: operations["withdrawSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}/submissions/{submissionId}/test-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** 試用チケットの一覧 */
        get: operations["listTestTickets"];
        put?: never;
        /** 試用チケットを発行（7 日） */
        post: operations["issueTestTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 審査待ち（awaiting_review・in_review、古い順） */
        get: operations["listReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/package": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** パッケージ・アイコンの取得先（署名付き URL、5 分） */
        get: operations["getSubmissionPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/sample-prompts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** 見本用のプロンプト（station-format が組み立てたもの） */
        get: operations["getSamplePrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI に話させた見本を保存（AI の出力だけ。1MB まで） */
        post: operations["saveSamples"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** 審査の記録（見本を含む） */
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 審査を始める（awaiting_review → in_review） */
        post: operations["startReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 審査を戻す（in_review → awaiting_review） */
        post: operations["releaseReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 承認（in_review → approved。リストを作り直す） */
        post: operations["approveSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/return": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 差し戻し（in_review → returned） */
        post: operations["returnSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/submissions/{submissionId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 却下（in_review → rejected） */
        post: operations["rejectSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/channels/{channelId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取り下げ（リストから消し、revoked に 7 日載せる） */
        post: operations["revokeChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 配信元の一覧（新しい順） */
        get: operations["listPublishers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        /** 配信元 */
        get: operations["getPublisher"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        /** 配信元のチャンネル */
        get: operations["listPublisherChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 配信元を停止（公開中のチャンネルはそのまま） */
        post: operations["suspendPublisher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 停止を解く */
        post: operations["resumePublisher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}/limits": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        get?: never;
        /** 上限を変える（省いた項目は既定値に戻る） */
        put: operations["setPublisherLimits"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/key-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 移し替えの申し出（既定は requested、古い順） */
        get: operations["listKeyTransfers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}/key-transfers/{transferId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移し替えを承認（審査待ちの申請は差し戻す。リストを作り直す） */
        post: operations["approveKeyTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publishers/{publisherId}/key-transfers/{transferId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移し替えを認めない（新しい鍵は外す） */
        post: operations["rejectKeyTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/signing-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 署名鍵の一覧 */
        get: operations["listSigningKeys"];
        put?: never;
        /** KMS の鍵を署名鍵として登録（公開鍵は KMS から取得する） */
        post: operations["registerSigningKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/keysets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 鍵セットの履歴（新しい順） */
        get: operations["listKeysets"];
        put?: never;
        /** ルート鍵が署名した鍵セットを登録（リストを作り直す） */
        post: operations["registerKeyset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開の履歴（新しい順） */
        get: operations["listPublications"];
        put?: never;
        /** 今すぐ作り直して公開する */
        post: operations["republish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 操作の記録（month と target のどちらか 1 つ） */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Ulid: string;
        ChannelId: string;
        AccountId: string;
        Base64Url: string;
        Rev: number;
        Problem: {
            /** @default about:blank */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description 問い合わせ用の要求 ID */
            instance?: string;
            /** @enum {string} */
            code: "invalid_request" | "invalid_signature" | "challenge_invalid" | "keyset_invalid" | "unauthorized" | "forbidden" | "publisher_not_active" | "not_found" | "already_registered" | "channel_id_taken" | "account_id_taken" | "key_already_bound" | "transfer_pending" | "limit_reached" | "pending_submission_exists" | "invalid_state" | "version_not_newer" | "precondition_failed" | "precondition_required" | "payload_too_large" | "quota_exceeded" | "throttled" | "internal";
            errors?: {
                /** @description JSON Pointer */
                path: string;
                message: string;
            }[];
        };
        Me: {
            sub: string;
            roles: ("publisher" | "operator")[];
            publisher?: components["schemas"]["Publisher"] | null;
        };
        /** @enum {string} */
        PublisherStatus: "pending_key" | "active" | "suspended" | "deleted";
        PublisherInput: {
            displayName: string;
            /** @description 審査・移し替えの連絡先 */
            contact: string;
        };
        PublisherPatch: {
            displayName?: string;
            contact?: string;
        };
        Limits: {
            /** @default 5 */
            channels: number;
            /** @default 20 */
            uploadsPerDay: number;
            /** @default 10 */
            ticketsPerDay: number;
        };
        LimitsOverride: {
            channels?: number;
            uploadsPerDay?: number;
            ticketsPerDay?: number;
        };
        Usage: {
            channels: number;
            uploadsToday: number;
            ticketsToday: number;
        };
        Publisher: {
            publisherId: components["schemas"]["Ulid"];
            displayName: string;
            /** @description 本人と運用者だけに返す */
            contact?: string;
            status: components["schemas"]["PublisherStatus"];
            statusReason?: string;
            activeAccountId?: components["schemas"]["AccountId"] | null;
            limits: components["schemas"]["Limits"];
            usage: components["schemas"]["Usage"];
            rev: components["schemas"]["Rev"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        KeyChallenge: {
            nonce: components["schemas"]["Ulid"];
            /** @description これの UTF-8 に Ed25519 で署名する */
            message: string;
            /** Format: date-time */
            expiresAt: string;
        };
        KeyProof: {
            nonce: components["schemas"]["Ulid"];
            publicKey: components["schemas"]["Base64Url"];
            signature: components["schemas"]["Base64Url"];
        };
        PublisherKey: {
            accountId: components["schemas"]["AccountId"];
            publicKey: components["schemas"]["Base64Url"];
            /** @enum {string} */
            status: "active" | "pending_transfer" | "unbound";
            /** Format: date-time */
            boundAt: string;
            /** Format: date-time */
            unboundAt?: string;
            unboundReason?: string;
        };
        /** @enum {string} */
        KeyTransferState: "requested" | "approved" | "rejected" | "cancelled";
        KeyTransferInput: components["schemas"]["KeyProof"] & {
            /** @enum {string} */
            reason: "lost" | "leaked" | "other";
            publicReason: string;
            note?: string;
        };
        Verification: {
            /** @description 例 登録済みの連絡先への返信 */
            method: string;
            detail: string;
        };
        KeyTransfer: {
            transferId: components["schemas"]["Ulid"];
            publisherId: components["schemas"]["Ulid"];
            fromAccountId: components["schemas"]["AccountId"];
            toAccountId: components["schemas"]["AccountId"];
            /** @enum {string} */
            reason: "lost" | "leaked" | "other";
            publicReason: string;
            note?: string;
            state: components["schemas"]["KeyTransferState"];
            verification?: components["schemas"]["Verification"];
            decisionReason?: string;
            returnedSubmissions?: components["schemas"]["Ulid"][];
            rev: components["schemas"]["Rev"];
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        ListedPackage: {
            /** Format: uri */
            url: string;
            sha256: string;
            size: number;
            format: number;
        };
        /** @description リストの channels[] の 1 件になる内容（DM-001 M-8） */
        LatestApproved: {
            submissionId: components["schemas"]["Ulid"];
            version: number;
            publisher: components["schemas"]["AccountId"];
            name: string;
            summary: string;
            description?: string;
            lang: string[];
            tags?: string[];
            regions?: string[];
            icon: {
                /** Format: uri */
                url: string;
                sha256: string;
            };
            package: components["schemas"]["ListedPackage"];
            minAppVersion: number;
            /** Format: date-time */
            approvedAt: string;
        };
        Channel: {
            channelId: components["schemas"]["ChannelId"];
            publisherId: components["schemas"]["Ulid"];
            /** @enum {string} */
            status: "active" | "revoked";
            pendingSubmissionId?: components["schemas"]["Ulid"] | null;
            latestApproved?: components["schemas"]["LatestApproved"] | null;
            /** @description 今のリストに載っているか */
            listed?: boolean;
            publisherChange?: {
                from?: components["schemas"]["AccountId"];
                /** Format: date-time */
                at?: string;
                reason?: string;
                /** Format: date-time */
                until?: string;
            } | null;
            revocations?: {
                versions?: number[];
                reason: string;
                /** @enum {string} */
                severity: "high" | "low";
                /** Format: date-time */
                revokedAt: string;
            }[];
            rev: components["schemas"]["Rev"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        SubmissionState: "uploading" | "validating" | "validation_failed" | "awaiting_review" | "in_review" | "approved" | "returned" | "rejected" | "withdrawn" | "expired" | "superseded" | "revoked";
        SubmissionInput: {
            description?: string;
            tags?: string[];
            regions?: string[];
            /** @description 運用者への説明 */
            note?: string;
        };
        Validation: {
            ok: boolean;
            errors: {
                /** @description API-003 のエラーコード、または bad_icon・id_mismatch・publisher_mismatch・version_not_newer */
                code: string;
                detail: string;
            }[];
            /** @description 必要なアプリの段（API-003 確認の手順 10） */
            appStage?: number;
            /** Format: date-time */
            checkedAt: string;
            validatorVersion: string;
        };
        Finding: {
            /** @description 審査基準の項目番号（例 2.2） */
            item: string;
            detail: string;
        };
        Decision: {
            /** @enum {string} */
            action: "approve" | "return" | "reject";
            findings?: components["schemas"]["Finding"][];
            message?: string;
            /** Format: date-time */
            at: string;
        };
        Submission: {
            submissionId: components["schemas"]["Ulid"];
            channelId: components["schemas"]["ChannelId"];
            /** @description パッケージの channel.json から（機械審査の後） */
            version?: number | null;
            accountId: components["schemas"]["AccountId"];
            state: components["schemas"]["SubmissionState"];
            description?: string;
            tags?: string[];
            regions?: string[];
            note?: string;
            sha256?: string | null;
            size?: number | null;
            validation?: components["schemas"]["Validation"] | null;
            decision?: components["schemas"]["Decision"] | null;
            /** Format: date-time */
            submittedAt?: string | null;
            /** Format: date-time */
            decidedAt?: string | null;
            rev: components["schemas"]["Rev"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PresignedPost: {
            /** Format: uri */
            url: string;
            fields: {
                [key: string]: string;
            };
            maxBytes: number;
        };
        SubmissionCreated: {
            submission: components["schemas"]["Submission"];
            uploads: {
                package: components["schemas"]["PresignedPost"];
                icon: components["schemas"]["PresignedPost"];
            };
            /** Format: date-time */
            uploadExpiresAt: string;
        };
        SignedDocument: {
            payload: components["schemas"]["Base64Url"];
            keyId: string;
            sig: components["schemas"]["Base64Url"];
        };
        TestTicket: {
            submissionId: components["schemas"]["Ulid"];
            document: components["schemas"]["SignedDocument"];
            /** @description QR コードにする文字列（API-002 の試用チケット） */
            qr: string;
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        SamplePrompts: {
            /** @description 組み立てた station-format の版 */
            generatedBy: string;
            scenarios: {
                id: string;
                label: string;
                system: string;
                user: string;
            }[];
        };
        SamplesInput: {
            service: string;
            model: string;
            items: {
                scenarioId: string;
                output: string;
            }[];
        };
        Review: {
            reviewerSub: string;
            /** @enum {string} */
            action: "start" | "release" | "approve" | "return" | "reject";
            findings?: components["schemas"]["Finding"][];
            message?: string;
            samples?: {
                samplesId: string;
                service: string;
                model: string;
                items?: {
                    scenarioId?: string;
                    output?: string;
                }[];
            }[];
            /** Format: date-time */
            at: string;
        };
        ApproveInput: {
            samplesIds?: string[];
            message?: string;
        };
        FindingsInput: {
            findings: components["schemas"]["Finding"][];
            message?: string;
            samplesIds?: string[];
        };
        RevokeInput: {
            /** @description 省くとすべての版 */
            versions?: number[];
            /** @description 利用者に見せる理由 */
            reason: string;
            /** @enum {string} */
            severity: "high" | "low";
        };
        ReasonInput: {
            reason: string;
        };
        SigningKey: {
            keyId: string;
            kmsKeyArn: string;
            publicKey: components["schemas"]["Base64Url"];
            /**
             * Format: date-time
             * @description 鍵セットに載ってから決まる
             */
            notBefore?: string | null;
            /** Format: date-time */
            notAfter?: string | null;
            /** @enum {string} */
            status: "registered" | "active" | "retiring" | "revoked";
        };
        Keyset: {
            seq: number;
            document: components["schemas"]["SignedDocument"];
            keyIds?: string[];
            revokedKeyIds?: string[];
            /** Format: date-time */
            registeredAt: string;
        };
        Publication: {
            seq: number;
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            expiresAt: string;
            sha256: string;
            size: number;
            keyId: string;
            /** @enum {string} */
            trigger: "approve" | "revoke" | "transfer" | "keyset" | "daily" | "manual";
            channelCount: number;
            revokedCount: number;
        };
        AuditEvent: {
            eventId: components["schemas"]["Ulid"];
            /** Format: date-time */
            at: string;
            /** @description 運用者にだけ返す */
            actorSub?: string;
            /** @enum {string} */
            actorRole: "publisher" | "operator" | "system";
            action: string;
            target: string;
            reason?: string;
            detail?: Record<string, never>;
        };
    };
    responses: {
        /** @description エラー（RFC 9457） */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 配信元 */
        Publisher: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Publisher"];
            };
        };
        /** @description チャンネル */
        Channel: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Channel"];
            };
        };
        /** @description チャンネルの一覧 */
        ChannelList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Channel"][];
                };
            };
        };
        /** @description 申請 */
        Submission: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Submission"];
            };
        };
        /** @description 判定後の申請と公開の状況 */
        Decision: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    submission: components["schemas"]["Submission"];
                    /**
                     * @description approve は pending（公開の Lambda を呼んだ）、return・reject は none
                     * @enum {string}
                     */
                    publication: "pending" | "none";
                };
            };
        };
        /** @description 鍵の移し替え */
        KeyTransfer: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["KeyTransfer"];
            };
        };
        /** @description 操作の記録（新しい順） */
        AuditPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["AuditEvent"][];
                    nextCursor?: string | null;
                };
            };
        };
    };
    parameters: {
        /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
        IfMatch: string;
        Cursor: string;
        Limit: number;
        ChannelId: components["schemas"]["ChannelId"];
        SubmissionId: components["schemas"]["Ulid"];
        PublisherId: components["schemas"]["Ulid"];
        TransferId: components["schemas"]["Ulid"];
    };
    requestBodies: never;
    headers: {
        /** @description `"{rev}"`。変える操作の `If-Match` に送る */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyPublisher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    registerPublisher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublisherInput"];
            };
        };
        responses: {
            201: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    deleteMyPublisher: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 自分の publisherId（打ち間違い防止） */
                    confirm: string;
                };
            };
        };
        responses: {
            /** @description 退会した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateMyPublisher: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublisherPatch"];
            };
        };
        responses: {
            200: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    createKeyChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一度きりの文字列 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyChallenge"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMyKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 鍵 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PublisherKey"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    bindFirstKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyProof"];
            };
        };
        responses: {
            /** @description 紐づけた鍵 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMyKeyTransfers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 申し出 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["KeyTransfer"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    requestKeyTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyTransferInput"];
            };
        };
        responses: {
            201: components["responses"]["KeyTransfer"];
            default: components["responses"]["Error"];
        };
    };
    cancelKeyTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["KeyTransfer"];
            default: components["responses"]["Error"];
        };
    };
    listMyHistory: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditPage"];
            default: components["responses"]["Error"];
        };
    };
    listMyChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ChannelList"];
            default: components["responses"]["Error"];
        };
    };
    registerChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    channelId: components["schemas"]["ChannelId"];
                };
            };
        };
        responses: {
            201: components["responses"]["Channel"];
            default: components["responses"]["Error"];
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Channel"];
            default: components["responses"]["Error"];
        };
    };
    listSubmissions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 申請 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Submission"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionInput"];
            };
        };
        responses: {
            /** @description 申請とアップロード先 */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionCreated"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Submission"];
            default: components["responses"]["Error"];
        };
    };
    withdrawSubmission: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Submission"];
            default: components["responses"]["Error"];
        };
    };
    listTestTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 試用チケット */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TestTicket"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    issueTestTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 試用チケット */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestTicket"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listReviewQueue: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 審査待ちの申請 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Submission"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSubmissionPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得先 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        packageUrl: string;
                        /** Format: uri */
                        iconUrl: string;
                        /** Format: date-time */
                        expiresAt: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSamplePrompts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 場面ごとのプロンプト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamplePrompts"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveSamples: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SamplesInput"];
            };
        };
        responses: {
            /** @description 保存した見本 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        samplesId: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 審査の記録 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Review"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startReview: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Submission"];
            default: components["responses"]["Error"];
        };
    };
    releaseReview: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Submission"];
            default: components["responses"]["Error"];
        };
    };
    approveSubmission: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveInput"];
            };
        };
        responses: {
            200: components["responses"]["Decision"];
            default: components["responses"]["Error"];
        };
    };
    returnSubmission: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingsInput"];
            };
        };
        responses: {
            200: components["responses"]["Decision"];
            default: components["responses"]["Error"];
        };
    };
    rejectSubmission: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingsInput"];
            };
        };
        responses: {
            200: components["responses"]["Decision"];
            default: components["responses"]["Error"];
        };
    };
    revokeChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeInput"];
            };
        };
        responses: {
            200: components["responses"]["Channel"];
            default: components["responses"]["Error"];
        };
    };
    listPublishers: {
        parameters: {
            query?: {
                status?: components["schemas"]["PublisherStatus"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 配信元 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Publisher"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPublisher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    listPublisherChannels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ChannelList"];
            default: components["responses"]["Error"];
        };
    };
    suspendPublisher: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            200: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    resumePublisher: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            200: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    setPublisherLimits: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                publisherId: components["parameters"]["PublisherId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LimitsOverride"] & {
                    reason: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Publisher"];
            default: components["responses"]["Error"];
        };
    };
    listKeyTransfers: {
        parameters: {
            query?: {
                state?: components["schemas"]["KeyTransferState"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 申し出 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["KeyTransfer"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    approveKeyTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                publisherId: components["parameters"]["PublisherId"];
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    verification: components["schemas"]["Verification"];
                };
            };
        };
        responses: {
            200: components["responses"]["KeyTransfer"];
            default: components["responses"]["Error"];
        };
    };
    rejectKeyTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得したときの `ETag`。ないと 428、違うと 412 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                publisherId: components["parameters"]["PublisherId"];
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            200: components["responses"]["KeyTransfer"];
            default: components["responses"]["Error"];
        };
    };
    listSigningKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 署名鍵 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SigningKey"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    registerSigningKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    keyId: string;
                    kmsKeyArn: string;
                };
            };
        };
        responses: {
            /** @description 署名鍵 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listKeysets: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 鍵セット */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Keyset"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    registerKeyset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    document: components["schemas"]["SignedDocument"];
                };
            };
        };
        responses: {
            /** @description 鍵セット */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyset"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPublications: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開の記録 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Publication"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    republish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonInput"];
            };
        };
        responses: {
            /** @description 公開の Lambda を呼んだ */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                month?: string;
                /** @description 例 `CH#kamakura-history`、`PUB#01J…` */
                target?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditPage"];
            default: components["responses"]["Error"];
        };
    };
}
